program_scope:
  company_name: T-Mobile
  base_domain: t-mobile.com
  wildcard_urls:
  - '*.t-mobile.com'
  in_scope_urls:
  - account.t-mobile.com
  - metrobyt-mobile.com
  - sprint.com
  - t-mobile.com
  - api.t-mobile.com
  - tfb.t-mobile.com
  - devedge.t-mobile.com
  - tess.service-now.com
  - digits.t-mobile.com
  - api.vistarmedia.com
  - packages.cortexpowered.com
  - api.vistarmedia.eu
  - production-dynam-creative.vistarmedia.com
  - storybook.vistarmedia.com
  - creatives.vistarmedia.com
  - sflower.cortexpowered.com
  - production-delivery-metrics-svc.vistarmedia.com
  - maps.vistarmedia.com
  - transcodes-cdn.vistarmedia.com
  - assets-cdn.vistarmedia.com
  - docker-staging.adstruc.com
  - staging-trafficking.vistarmedia.com
  - job-svc-b.vistarmedia.com
  - docsite.vistarmedia.com
  - sfleet.cortexpowered.com
  - audience-builder.vistarmedia.com
  - staging-login.vistarmedia.com
  - clients.adstruc.com
  - demo.adstruc.com
  in_scope_ips:
  - 10.72.218.66
  - 10.62.252.214
  out_of_scope_urls:
  - '*.sprint.net'
  - '*/self-service-*'
  - '*.mobile.uscc.net'
  - '*.mobile.uscc.com'
  - '*.moengage.com'
  out_of_scope_ips: []
  out_of_scope_attack_vectors:
  - Clickjacking on pages with no sensitive data or actions
  - Unauthenticated/logout/logon Cross Site Request Forgery (CSRF)
  - Attacks requiring Man-in-the-Middle or physical access to a user's device
  - Previously known vulnerable libraries without a working Proof of Concept
  - Use of outdated software/library version(s)
  - Comma Separated Values (CSV) Injection without demonstrating a vulnerability
  - DoS
  - DDoS
  - OPTIONS or TRACE HTTP method enabled
  - Missing best practices in SSL/TLS configuration
  - Expired SSL Certificates
  - Content spoofing and text injection issues without showing an attack vector/without
    being able to modify HTML/CSS
  - Cookies that lack HTTP Only or Secure settings for non-sensitive data
  - social engineering
  - Presence of autocomplete functionality in form fields
  - Lack of email address verification during account registration
  - Missing security headers
  - Mixed content issues
  - Tabnabbing
  - Reports of credentials exposed by other data breaches/known credential list
  - Cross-Site Scripting
  - Cache poisoning
  - Open redirects
  rate_limit: 5
  custom_headers:
    X-Bug-Bounty: BugCrowd-kiddulu
  notes: ''
auth_profiles:
  default:
    type: dat1kidd916@gmail.com
    token: 9Form1By6$
tool_configs: {}
callback_server:
  host: 0.0.0.0
  port: 8443
